# _config.yml
title: Bioelectronics Hub
author: Maryam Habibollahi
description: Research Fellow in Integrated Bioelectronics at University College London
theme: minima

# GitHub Pages deployment
baseurl: "/bioelectronics-hub"

# Include favicon and keep images
include:
  - favicon.ico.png

keep_files:
  - assets

# navigation links
header_pages:
  - research.md
  - teaching.md
  - publications.md

